# Generated by Django 2.2.8 on 2019-12-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=300)),
                ('bairro', models.CharField(max_length=300)),
                ('localidade', models.CharField(max_length=300)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=4)),
                ('dataHora', models.DateField()),
                ('imagem', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
    ]
