# Generated by Django 2.2.8 on 2019-12-10 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('logradouro', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=4)),
                ('cep', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=300)),
                ('localidade', models.CharField(max_length=300)),
                ('uf', models.CharField(max_length=2)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('imagem', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
